### ISSUE TITLE
Pushing apps to Higher Environmet from Sandbox to Dev/Prod

### ISSUE THREAD

**Issue by saravanakumargs** [athenahealth/apiserver-athenaFlex#174]
HI,

We are able to generate the Token and verify corresponding details in sandbox.

Now, we are planning to move to Dev environment and then to production. 

Please let us know the process or corresponding link to follow to submit.

Thanks,
Saravanakumar GS.

**Comment by AjeetYadav07** [comment]
Production API Server URLs come from athenaPractice and athenaFlow customers. You must work with them to get the API Server URL(s) they have configured to be accessible through the external, public Internet. If you have a cloud application, you may need to work with them to get a connection from your cloud whitelisted so your app can connect to their network(s).
If aPractice/aFlow customers have both test and production systems, you'll need to complete the integration in a test instance before it is moved to the production instance.
"Obtaining Application Credentials" under API Resources > Overview > Security at https://mydata.athenahealth.com/fhirapidoc has a short description of app credentials provided as client id and secret.
If different redirect URLs will be used between pre-production and production, then you will need to register a new app at https://mydata.athenahealth.com/my-apps because the redirect URLs are associated with each client id.
If a cloud app vendor has multiple deployment environments such as staging and production, you are required to do one of the following to manage client id(s) and secret(s) for your app.
•	Register multiple copies of your app on the mydata.athenahealth.com Dev Portal if the redirect URLs are different between stage and production
•	Register a single copy of your app with multiple redirect URLs including the list of both stage and production redirect URLs.
Provider credentials must be obtained from the athenaPractice/athenaFlex customers who deploy/configure the FHIR servers with their B2B Azure Active Directories.  Just as athenahealth gives sample provider credentials for our API sandbox FHIR server, our customers must give credentials for providers authorized to access their FHIR servers.
There is no separate approval process to use an application in production.
