### ISSUE TITLE
Issues reading external attachments on some documents

### ISSUE THREAD

**Issue by mikeseale** [athenahealth/apiserver-athenaFlex#180]
There are some external attachments in our EMR that we are having trouble pulling through the FHIR API.  Currently using version CPS 12.3's version of FHIR.  We are able to open these PDF attachments inside the EMR, but we get a file validation error in the log when attempting to pull binary from FHIR API.

/fhir/Binary/EXT-1888577964524300

**Error in log:**
BCW356E05: File validation failed for \\server_name/Documents$/Path/ToThe/File/File.pdf-The file for ID: EXT-1888577964524300 does not exist in the specified location.

I have confirmed that the file does exist in this location, and it can be viewed within the EMR.

**Comment by Torin-Shepard-athena** [comment]
There is limited support for external attachments due to complexities in managing and configuring access to network resources.

The accepted beginning path components are configured in the SUPPORTEDMONIKERS entry in mappings.properties file for CPS API Server.

#Supported Monikers
SUPPORTEDMONIKERS=http|C:|D:|\\\\

There still may be issues if CPS Interop Server is not able to connect to the specified path
- Monikers with file paths for C or D drives often refer to disk drives accessible from CPS client application but not accessible to any of the JBoss servers.
- Universal naming convention for internal network paths may or may not work depending on whether CPS Interop Server is configured to be able to access those resources.
- Some simple URLs for resources accessed through http will work assuming Interop server is able to establish simple URL connection to the requested web resource.

**Comment by mikeseale** [comment]
Thank you for responding, Torin.

We have been working hard on this error for the last few weeks.  We finally found that the interop didn't have access to the path specified; however, we didn't realize that the account needing access to the share path was the account running the interop service.  We ended up creating an AD service account that would run the interop JBOSS, and then gave that AD account access to the file share.
