### ISSUE TITLE
Appointments in sandbox do not have a Status

### ISSUE THREAD

**Issue by healthbanksdev** [athenahealth/apiserver-athenaFlex#183]
Hi, I'm attempting to search the appointments in the sandbox by the appointment status (eg. Appointment?location=FAC-3&status=fulfilled) but I receive no results. When I remove this filter and see all appointments, I realize that there doesn't appear to be a status element in the appointment JSON at all.  Please advise, thanks.

**Comment by AjeetYadav07** [comment]
Hi @healthbanksdev, In sandbox machine we have status='fulfilled' for below ids of Appointment resource:
https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment/314
https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment/312
https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment/310

**Comment by healthbanksdev** [comment]
Hi, I don't believe I have access to that sandbox.  I'm pointing to: https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir.  Could you let me know what appointments at this sandbox have a fulfilled status?

**Comment by healthbanksdev** [comment]
Also, please note that another problem I'm experiencing is that the Appointment endpoint results do not contain a "status" element, so I am unable to determine the status of any appointments.  eg. Appointment 258:  https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment/258?_format=json

**Comment by Torin-Shepard-athena** [comment]
@healthbanksdev
You have access to both of the machines with 2 different product versions.
CPS 12.3: https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer
athenaPractive V20: https://apsandbox.fhirapi.athenahealth.com/demoAPIServer
The test provider credentials are authorized for both machines.

@AjeetYadav07 commented about cpsapisandbox which has a few more Appointment resources than apsandbox.

In general, you can assume the absence of Appointment.status element is equivalent to status = pending.

Are you aware of the :missing modifier defined for FHIR searches?
http://hl7.org/fhir/dstu2/search.html#modifiers

The following query will return all Appointments that have a status.

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_format=json&_lastUpdated=le2010-01-01&_summary=data&location=Location%2FFAC-3&_count=100&status:missing=false

Instead of relying on demonstration content, you could consider adding your own appointments.  Issues #21 and #165 have samples of the POST request body for creating an Appointment.

**Comment by healthbanksdev** [comment]
Excellent, thanks!
