### ISSUE TITLE
Unable to get Patients, Appointments & Bills.

### ISSUE THREAD

**Issue by ARCSIndia** [athenahealth/apiserver-athenaFlex#184]
I have generated request response for Patients, Appointments.

Patient & Appointment API Doesn't return any records on response. (Attached Request response).

Patient not returned for LastmodifiedDate since 2010 & Appointment Not returned for Any location we get through Location API.
[Fiddler_Request_Response.zip](https://github.com/athenahealth/apiserver-athenaFlex/files/6559980/Fiddler_Request_Response.zip)

Also please suggest Billing APIs Endpoint.

**Comment by ARCSIndia** [comment]
@Torin-Shepard-athena Please take a look and Provide valuable response.

**Comment by AjeetYadav07** [comment]
Hi @ARCSIndia, in request https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_format=json&_summary=data&location=1225648424001060&_lastUpdated=2010-01-01
search parameter location value is incorrect and don't use strict equality condition for _lastupdated. location search parameter value is a facilityId. Corrected request: 
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_format=json&_summary=data&location=Location/FAC-3&_lastUpdated=le2010-01-01
Similarly for Patient API https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient?_format=json&_summary=data&_lastUpdated=le2010-01-01

**Comment by ARCSIndia** [comment]
@AjeetYadav07 I capture the Request response using the URL for Appointment & Patient.
There is no Appointment & only patient since 2010.

Also capture Posting response there is no location, Provider, Procedure details on response.
[Fiddler_Request_Response.zip](https://github.com/athenahealth/apiserver-athenaFlex/files/6576071/Fiddler_Request_Response.zip)

**Comment by Torin-Shepard-athena** [comment]
@ARCSIndia
It is true there are no appointments after 2010.  athenaPractice demonstration databases contain historical appoinment dates that are not maintained/updated to have the current year.

As mentioned in our API documentation for practice management resources: HL7 FHIR DSTU Release 2.0 does not provide a resource to access patient payments or account balances.  Since this information is important for practice management, we created 2 different extensions of the Basic resource that are accessed through operations: fhir/$Posting and fhir/$Account

The "FHIR Documentation" link at the bottom right of our Dev Portal has a link to our API documentation in similar format that you see on HL7 FHIR web site.
https://docs.mydata.athenahealth.com/ge/ge-posting-profile-mappings.html
https://docs.mydata.athenahealth.com/ge/ge-account-profile.html
These pages show the fields/elements/extensions that are available in "Posting" and "Account" resources which give information about payments and patient accounts.

Use values in the subject and patientVisitId extension in the Posting resource to access the corresponding Account resource.

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/$Account?_format=json&subject=1442678386200620&patientVisitId=407

Account resources have Practitioner reference in account-doctorId extension and Organization reference in account-facilityid.
Organization.id values for Account resources have prefix DF.  This prefix can be replaced with FAC to access the equivalent Location resource.
Example: Organization/DF-3 is equivalent to Location/FAC-3.

Since FHIR DSTU2 does not have much support for practice management (PM) resources, financial information about charges for specific Procedures within a visit are currently _**not**_ available in our PM APIs.

**Comment by ARCSIndia** [comment]
@Torin-Shepard-athena Please also provide the details about patient Apies, only patient returned since 2010.

**Comment by Torin-Shepard-athena** [comment]
@ARCSIndia
At the time of this comment, GET https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient?_format=json&_summary=data&_lastUpdated=ge2011-01-01 returns a Bundle of 15 Patient resources.
- All 15 have Patient.meta.lastUpdated on or after beginning of 2011.
- 1 is a test patient for electronic prescribing with last updated date December 2015
  - This is the last patient ever created by athena.
- 14 have a last updated date after mid-September 2020.
  - These patients are created by other users of this API Sandbox machine.
  - There is no guarantee there will be other resources related to these patients.

The default factory content of demonstration DB has patients (and other content) created many years ago.  There are likely practice management and/or clinical resources related to patients created before 2011.

Any patients (or other resource types) returned with last updated dates after 2015 were created by other 3rd party developers who perform POST and/or PUT requests to write to Patient resources.  Please remember apsandbox.fhirapi.athenahealth.com FHIR Server is shared by all developers who are building applications that integrate with athenaPractice.

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/metadata
https://docs.mydata.athenahealth.com/ge/CPS-metadata.html
https://mydata.athenahealth.com/fhirapidoc > Individual resource pages > Supported Operations

The metadata for this FHIR Server and our API documentation shows which resource types support create and update operations.

**Comment by ARCSIndia** [comment]
I already provided the response of get Patient since 2010 but only receive 1 patient details not 15.

Currently I required to call GET Patient Not Create & Update.


Any patients (or other resource types) returned with last updated dates after 2015 were created by other 3rd party developers who perform POST and/or PUT requests to write to Patient resources. Please remember apsandbox.fhirapi.athenahealth.com FHIR Server is shared by all developers who are building applications that integrate with athenaPractice.
=> On which server I am getting only patient of my own account.

**Comment by ARCSIndia** [comment]
@Torin-Shepard-athena I already provided the response of get Patient since 2010 but only receive 1 patient details not 15.

Currently I required to call GET Patient Not Create & Update.

**Comment by ARCSIndia** [comment]
@Torin-Shepard-athena @AjeetYadav07 I am waiting for your response.

**Comment by ARCSIndia** [comment]
Still waiting for your response.

**Comment by AjeetYadav07** [comment]
@ARCSIndia
The url :  https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient?_format=json&_summary=data&_lastUpdated=ge2011-01-01  will return 15 results. Try these ids to get required patient:
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1937646538460860",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1935412834436190",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1935325955434980",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1935325955434970",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1935325955434960",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1935325955434950",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1916510818339810",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1916493784336190",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1916439556334990",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1916401682334200",
"https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1915905399331300", "https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1915434311330760", "https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1239620410000620", "https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1225794129001060",  "https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1009843200000000".
These are the patient id which have lastUpdated dates since 2011.

**Comment by ARCSIndia** [comment]
Using the same Url https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient?_format=json&_summary=data&_lastUpdated=ge2011-01-01

We only get 1 patient records.(Attached postman request response).

[postman request.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/6646486/postman.request.txt)
[postman response.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/6646487/postman.response.txt)

**Comment by Torin-Shepard-athena** [comment]
@ARCSIndia
Please let us know how you are authenticating.  When @AjeetYadav07 and I perform this FHIR query using the sample hwinston@sboxprovtenant.com provider account, we get multiple records.
I suggest you send email to athenaInterop@athenahealth.com.  If we have your personal email address, then we can schedule a call with you and observe the complete process from getting auth code, exchanging for access token, and making FHIR API calls.

**Comment by ARCSIndia** [comment]
Using following Url with credentials hwinston@sboxprovtenant.com provider account, we get only record.
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient%20offline_access&response_type=code%20id_token&redirect_uri=https://portal.redspotinteractive.com&aud=https://apsandbox.fhirapi.athenahealth.com/demoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL3d3dy5jZW50cmljaXR5dXNlcnMuY29tXC8iLCJncmFudF90eXBlcyI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwiaXNzIjoiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tIiwicmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvcG9ydGFsLnJlZHNwb3RpbnRlcmFjdGl2ZS5jb20iXSwidG9rZW5fZW5kcG9pbnRfYXV0aF9tZXRob2QiOiJjbGllbnRfc2VjcmV0X2Jhc2ljIiwic29mdHdhcmVfaWQiOiIxLjAuMCIsIm5hdGl2ZV9jbGllbnQiOmZhbHNlLCJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb21cL29hdXRoMi5jbGFpbXNcL2FwcF9pZCI6ImNkY2Y4MzkxLTU5ZGItNGNmMy04ZTZkLTk4OWFhODFmYTRjOCIsImV4cCI6MTkyODMxODcyNiwiY2xpZW50X25hbWUiOiJSZWRzcG90SW50ZXJhY3RpdmUiLCJpYXQiOjE2MTI3ODU5MjYsImNvbnRhY3RzIjpbImFqYWluQHJlZHNwb3RpbnRlcmFjdGl2ZS5jb20iXSwicmVzcG9uc2VfdHlwZXMiOlsiY29kZSJdfQ.XfFIROARu-hkRmhRoloMowCrx0EetuKVKhMyGWP_Hq_utfyN4KZ1MYYbt8Gan1-Mydc--aGPF1jhnNGbsPQLEDxiHjbwKO-VIXUHFUs0U10k7vq2xHLi4EKmBXNtdpj4gu2lHyRdKsSIPpjpM3Ufv1NCgiywTQ16Y0nyNr54-MU

I sent you a mail on athenaInterop@athenahealth.com, with reference of this ticket.

**Comment by Torin-Shepard-athena** [comment]
@ARCSIndia @AjeetYadav07
Thank you for posting a copy of the authorize URL you are using.  This shows why you are getting only one record.

You followed example from "Construct the Access My Data URL" at https://mydata.athenahealth.com/access-the-apis.
scope=openid%20profile%20**patient/*.read%20launch/patient**

launch/patient scope causes FHIR Server to prompt you to select a specific patient.  The access token issued is authorized for only the one select patient.

This information is mentioned in the API Access page on our Developer Portal, but it may have have been overlooked.

**IMPORTANT**: Each patient account has one token assigned to it; each provider account includes a token for each patient under their care.

**Note**: The above sample call to the authorize endpoint requests an access token for a specific patient context by specifying the OAuth2 scopes for patient context (patient/*.read and launch/patient). These scopes will prompt you to select a patient. If you do not want to establish a patient context with your access token, then you may use other scopes that are available as part of the SMART on FHIR standard. See Scopes and Launch Context on the SMART technical documentation website.

If you want to have access to all the patients with the sample provider account, change the scope parameter to request user scope.
scope=openid%20profile%20**user/*.read**
