### ISSUE TITLE
How to get Access Token with out using Construct the Access My Data URL UI

### ISSUE THREAD

**Issue by rahul-chetu** [athenahealth/apiserver-athenaFlex#193]
Hi,

We understand that we can generate an authorization code for a work account as explained on the developer portal.

However, we do not want to generate authorization code using UI/ manual steps. We want to generate this authorization code automatically, through an API. We will then use this authorization code to schedule the appointments and post patient payment.

So our question is - can we generate this authorization code automatically through APIs?

**Comment by Torin-Shepard-athena** [comment]
@rahul-chetu Please see details posted in #177 Service Application Credentials

**Comment by stevencorona** [comment]
Hello,

We are also having trouble deciphering the steps necessary to connect to the API in a system-to-system fashion programmatically, without a user manually logging in via SSO or OAuth.

We've reviewed the API documentation and the details posted in #177, but still don't have a clear picture on:

1. If this workflow is actually possible
2. What the IT team needs to configure to generate appropriate credentials
3. What API calls we need to make, if any, to turn the credentials into a valid API token.

Appreciate any help.

**Comment by Torin-Shepard-athena** [comment]
@stevencorona
This workflow is possible and used by multiple apps that access APIs using system user account credentials.

athenaPractice and athenaFlow customers do the following.
- Create "system" user account in cloud AAD and on premise AD
- Add this user as member of "API Server User" group in athenaPractice or role in athenaFlow
- Grant this user appropriate permissions based on the FHIR resource types = APIs the App will access
- Share the AAD user name and password with the App developer/owner.

App owners do the following.
- Store the system user name and password as protected (preferably encrypted) configuration parameters
- Use the account credentials for this system user to create the basic authorization header in the GET request to the API Server token endpoint as described in "Notes on athenaPractice Native User Auth Flow.docx".
- The App will make the GET request to [base]/dbnameAPIServer/oauth2/token instead of Postman
- Extract access tokens from token endpoint response
- Repeat this process for each athenaPractice / athenaFlow system where the App will be used.
