### ISSUE TITLE
Patient MRN as identifier

### ISSUE THREAD

**Issue by BYUSHC** [athenahealth/apiserver-athenaFlex#195]
What is the correct syntax for running a patient search based on the MRN?  Is there a system ID for MRN?

FHIR website:  Search for the Medical Record Number 446053 - this is useful where the system id for the MRN is not known
GET [base]/Patient?identifier:otype=http://terminology.hl7.org/CodeSystem/v2-0203|MR|446053

**Comment by Torin-Shepard-athena** [comment]
@BYUSHC

You can search for Patient by identifier using only the value without the coding system.
GET [base]/Patient?identifier=446053 will return all identifiers with a matching value ignoring the code system.

If you want to request a value matched from only a specific coding system, then you will want to use the syntax identifier=system|value

Perform a Patient query and look for identifier element where identifier/system@value contains MRN.

Here is a sample from our API Sandbox.
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1239620410000620
``` xml
                <identifier>
                    <type>
                        <coding>
                            <system value="http://hl7.org/fhir/v2/0203"/>
                            <code value="MR"/>
                        </coding>
                    </type>
                    <system value="http://www.gehealthcare.com/fhir/cpsemr/namingsystem/MRN/Training"/>
                    <value value="MR-846-624"/>
                </identifier>
```
The "Training" part at the end of this URL corresponds to a license code for the individual CPS/CEMR/athenaPractice/athenaFlow system.

The aPractice V20 system on apsandbox.fhirapi.athenahealth.com uses a Training license.

Here is a sample URL to search for the Patient with this MRN value.
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient?identifier=http://www.gehealthcare.com/fhir/cpsemr/namingsystem/MRN/Training%7CMR-846-624

Notice the | character is URL-encoded as %7C because some tools like Postman do not URL-encode the | character in URL query strings.
https://github.com/postmanlabs/postman-app-support/issues/8775#issuecomment-659126717

**Comment by BYUSHC** [comment]
Thank you
