### ISSUE TITLE
How to search slots

### ISSUE THREAD

**Issue by rahul-chetu** [athenahealth/apiserver-athenaFlex#198]
I am building out functionality that would allow patients to search for available slots given the following criteria:

Date Range (start and end date)
Location(s)
Practitioner(s)
Appointment Types

Please advise, how we can get the slots based on the above criteria.

**Comment by Torin-Shepard-athena** [comment]
@rahul-chetu
See #20 for information about how to find Schedule resources using :missing modifier.
Schedule resources for rooms, equipment, other non-person objects do not have any actor reference.
Search for these with Schedule?actor:missing=true.

Schedule resources for people have actor reference to Practitioner.
Search for these with Schedule?actor:missing=false.

Example: Schedule/41 has actor element with reference to Practitioner.

You can search Slot resource by schedule parameter to get slots in a given Schedule.id
This indirectly gives a way to search by Practitioner since all Schedule resources are associated with a Practitioner.

The :missing modifier can be used to search Slot resources

The following query will return a Bundle of Slot resources that DO have type assigned.
Slot?schedule=41&slot-type:missing=false

For these resources, you can examine the type.coding elements to learn values that can be used for searching Slot by slot-type parameter.

The following query will return a Bundle of Slot resources that do NOT have any type assigned.
Slot?schedule=41&slot-type:missing=true
Many available slots are not assigned any type which would limit the types of appointments that can be scheduled in the slot.

You can search Slot by start.  You can use prefixes with date search parameters to search by a range.
Slot?schedule=41&start=ge2006-10-19&start=lt2006-10-20&_count=100 will return Slots in Schedule/41 with start on October 19, 2006.

Location is output in Slot.extension element where url contains slot-facility.
Unfortunately, searching by this extension element is NOT supported.
Example:
``` xml
  <extension url="http://hl7.org/fhir/StructureDefinition/ge-slot-facility">
    <valueString value="398"/>
  </extension>
```
This corresponds to Location/FAC-398.

See #168 for explanation about why Schedule resources can be read with user scope but cannot be read with patient scope.

**Comment by AjeetYadav07** [comment]
Closing this issue, if you have any question please raise a new ticket.
