### ISSUE TITLE
Unable to generate authorization code using Work Account

### ISSUE THREAD

**Issue by tthai4** [athenahealth/apiserver-athenaFlex#201]
I am trying to follow the instruction for API access but get stuck at the "Provider workflow: Generate authorization code using Work account" section.  In fact, I entered my dev portal userid/password that I have just created but kept getting error saying "AADSTS50020: User account 'tthai4@bwh.harvard.edu' from identity provider 'https://sts.windows.net/720edb1f-5c4e-4043-8141-214a63a7ead5/' does not exist in tenant 'FHIR Sandbox - Provider Access' and cannot access the application '45e8ea72-5bff-423e-b5a2-2dfc2b651f7b'(GE Healthcare API Server) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account."

Can you please advise me on this?  Thank you.

Regards,
Tien Thai

**Comment by Torin-Shepard-athena** [comment]
@tthai4

The "Access the APIs" page also explains: If you are using sandbox for testing, you can use our sample provider login credentials:
User Name: hwinston@sboxprovtenant.com

athenaPractice API Sandbox machines are configured to use sboxprovtenant B2B Azure Active Directory (AAD).  This B2B will authenticate only the sample user accounts athenahealth creates in this B2B.  You can use only hwinston@sboxprovtenant.com.

A similar configuration exists for all athenaPractice and athenaFlow customers.  They create users in their someuser@somedomain.com B2B AAD and also make sure those users (someuser extracted before the @ sign) are added into local AD and granted proper permissions/privileges in their on-premise system.

The B2C user accounts created on Dev Portal can be used for only logging into dev portal.  Dev Portal B2C accounts are not known to the B2B AAD configured for athena FHIR API Sandbox or athenaPractice/athenaFlow customer FHIR Servers.

**Comment by tthai4** [comment]
Hi Torin,

I used that userid and was able to get the authorization code.  However, I got the 500 error when requesting access token id with that authorization code.  Can you please check that out for us?  Thanks very much.

Best,
Tien Thai

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Torin-Shepard-athena** [comment]
This issue was caused by incorrect process and incomplete authorization flow.

In patient selection screen, you cannot right-mouse on “Select Patient” button, use browser “Inspect” tools, and copy the authorization code from that button.

The token POST request will rejected when the auth code is not yet associated with selected patient context.

launch/patient scope requires patient context to be set. If you do not click the Select Patient button (at least one of these buttons when multiple patients are listed), the internal process is not completed to associate the auth code with a selected patient.
