### ISSUE TITLE
API to get list of billing tickets

### ISSUE THREAD

**Issue by bmeanspay** [athenahealth/apiserver-athenaFlex#203]
I need to get a list of billing tickets for a location for a given day for a client that is using AthenaPractice.  Is there an API that would provide this information in order to retrieve charges for customer visits for that day?  

My second question is if we need to apply payments in real-time that have been made outside of AthenaPractice what would the API be to do that?

**Comment by Torin-Shepard-athena** [comment]
@bmeanspay
We currently do not have an API to get list of charges created for visits on a given day or facility/location.
We have the $PostPayment API to create payments that have been made outside of athenaPractice.  See #141 for more information.

**Comment by bmeanspay** [comment]
Thanks - Related to the first question, would there be an option through something like $Account operation to do a lookup by patient last name or will a more specific value like the patient id be required?  We are trying to determine the best approach to when a patient is at checkout to retrieve any amount due from that visit.

**Comment by Torin-Shepard-athena** [comment]
@bmeanspay
The API documentation at https://mydata.athenahealth.com lists the search parameters supported for $Account.
You are correct. $Account supports search by subject = patient id but not patient name.  You can search Patient resource to find the id needed to search $Account by subject.
$Account also supports search by visitDate and patientVisitId.

**Comment by Torin-Shepard-athena** [comment]
@bmeanspay
Using the API sandbox is probably the best way to see the elements returned.

Issue #141 has URLs for some sample resources by id and by a sample patient.
$Account?_id=000083
$Account?_id=000085
$Account?subject=1442678385550620 returns Bundle of 3 Account resources for this test patient.
TicketNo 000391 and VisitId 388
TicketNo 000390 and VisitId 387
TicketNo 000383 and VisitId 380

The footer on the current Dev Portal has a link to to "FHIR Documentation".  This link is broken due to work in progress on our V22 release which will support FHIR R4.

We have a "FHIR" flavor of our DSTU2 API documentation that will give some information.
https://docs.mydata.athenahealth.com/FHIR_API_Publish/index.html (note FHIR_API_Publish is added to the base URL)
Go to Implementation Guides > scroll to the bottom and go to GE Healthcare
https://docs.mydata.athenahealth.com/FHIR_API_Publish/ge/ge.html
From here you can get to the Account page.
https://docs.mydata.athenahealth.com/FHIR_API_Publish/ge/ge-account.html

https://docs.mydata.athenahealth.com/FHIR_API_Publish/ge/registry.html
This page has links to FHIR flavor of all the DSTU2 resource types supported by athenaPractice/athenaFlow.
Go to ge-account-profile.
https://docs.mydata.athenahealth.com/FHIR_API_Publish/ge/ge-account-profile.html
Go to Mappings tab for information about how athenaPractice DB fields are mapped to FHIR.

NOTE:  FHIR DSTU2 did not have a resource type to access patient account balances. Since this information is essential for practice management, we created an extension of the Basic resource to support this content which can be accessed via $Account operation.

FHIR R4 defines the [Account](https://hl7.org/fhir/r4/account.html ) resource type.  In our future V22 release that will support R4,  we will support R4 Account and instead of Basic.  We will keep several extensions that are still not available in the FHIR Account resource so we can maintain all the same elements that are available in earlier releases. During the transition to R4, apps will need to be migrated to read Account resources instead of performing the discontinued $Account operation.

**Comment by bmeanspay** [comment]
@Torin-Shepard-athena Would we be able to setup a call with our development team to ask some questions related to the APIs?

**Comment by Torin-Shepard-athena** [comment]
@bmeanspay Please send email to athenainterop@aol.com so we will have your email outside of GitHub to be able to schedule a call.  I am in Pacific time zone. Please suggest times which would work for you.  If feasible, please list your questions in case it helps us be better prepared to answer them.

**Comment by AjeetYadav07** [comment]
Marking this issue as closed. Please reopen if you still face any issues.
