### ISSUE TITLE
Authorize without entering credentials every time?

### ISSUE THREAD

**Issue by dwwinters** [athenahealth/apiserver-athenaFlex#207]
We have an application that will have multiple users and we don't want them to have to enter their credentials every time they use the app.  Is our best path forward to follow the instructions at the end of [Issue 177?](https://github.com/athenahealth/apiserver-athenaFlex/issues/177)

**Comment by Torin-Shepard-athena** [comment]
Can you please try including offline_access in the scope parameter for the authorize endpoint as described at the end of Issue #167?  When you present the auth code to the token endpoint, you should get a refresh token along with the access token.  The refresh token can be exchanged for a new access token until the refresh token life cycle time expires.

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20user/*.*%20offline_access&response_type=code%20id_token&redirect_uri={REDIRECT_URL}&aud=https%3A%2F%2Fapsandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id={CLIENT_ID}

**Comment by dwwinters** [comment]
Thanks for the response @Torin-Shepard-athena.  Is offline_access necessary for bypassing the microsoft login?  I don't understand the answer to the first question asked in [Issue 167](https://github.com/athenahealth/apiserver-athenaFlex/issues/167):

**Question**: Is there a way to get rid of https://login.microsoftonline.com/ login window
so that user credentials entered programmatically?
**[Response](https://github.com/athenahealth/apiserver-athenaFlex/issues/167#issuecomment-769954500)**: Please look at the metadata Conformance statement to bypass the https://login.microsoftonline.com/ login window by entering user credentials programmatically.

**Comment by Torin-Shepard-athena** [comment]
The comment about using metadata is misleading.  offline_access scope is used to request OAuth2 refresh token which can be used to bypass the prompt for user credentials on 2nd and subsequent accesses for the duration of the refresh token.  User of Microsoft login to get user credentials will always be required for the initial first login for a given user.

**Comment by dwwinters** [comment]
Thanks @Torin-Shepard-athena, that certainly clarifies things for me.

**Comment by AOCjcarr** [comment]
Hey @Torin-Shepard-athena , David is working with us on this API.  

This is the API I had mentioned a few weeks ago that we are triggering and utilized within an encounter form in athenaPractice.   The user triggers this API  by a button within the clinical content to initiate the process.   The API utility lives on a server within our environment and treated as a trusted API connection with these credentials.

Similar to eCRNow,  the need is for the authentication with the API AAD account to be passed within the FHIR call so that it is automatically authorized, as the clinical users should never need to login, nor do we want to setup every clinical user as an API account.

We do have a API AAD account that is setup that we have been utilizing for the testing in postman, and ultimately need it to be defined in the API for use by the  API utility for all calls to AP.

Right now the calls are working, but the AAD authorization is popping up, and trying to determine how to provide these credentials through the call.

**Comment by Torin-Shepard-athena** [comment]
@AOCjcarr
When an authorized user is logged into athenaPractice, we should be able to pass the logged in user and current patient context to a SMART on FHIR app to make authorized FHIR API calls as that user.  We may be able to create a solution if the button in the encounter form can use MEL_LAUNCH_SMARTAPP function to invoke use your "API utility" as a SMART on FHIR app.

The MEL function named MEL_LAUNCH_SMARTAPP can be embedded in an encounter form.
MEL_LAUNCH_SMARTAPP('https://your.domain.com/api_utility')
This MEL function would return a URL like the following.
https://https://your.domain.com/api_utility?launch={launch_code}&iss=https://your.domain.com/apracticedbAPIServer/fhir
If this MEL function is linked to a button, when the button is clicked, the SMART app will be invoked with this URL.

Expected behavior for a SMART App invoked with launch and iss parameters.
- App sends GET request to aP/aF FHIR Server authorize endpoint with parameters including the launch code it was given, its client id from mydata.athenahealth.com Dev Portal, and desired redirect_uri
- aP/aF FHIR server returns auth code to redirect URL in auth endpoint request from the App.
- App sends POST request to aP/aF FHIR Server token endpoint with client id + secret in https authorization header, and auth code and redirect_uri in the request body
- aP/aF FHIR server returns an access token to redirect URL in token endpoint request from the App

This approach may not work for triggering eCR Now because we currently do not support current encounter context in SMART app launch. If using this MEL function is not feasible or is problematic, then your API utility should be able to use service app credentials using the special system API AAD account as described in #177.

**Comment by AOCjcarr** [comment]
Thanks @***@***.***>

From what you describe, I believe it is the solution under 177 that David is trying to accomplish that we have provided him the credentials but attempting to get it to pass back properly to aP to avoid the login popup.    He is working on an update now to update the call to use the aPI AAD account and password so we can test to see  if that works when we meet on Thursday.  Hopefully that will resolve for now.

Interseing on the MEL Launch Smartapp..   Would the app be able to identify the SDID and document owner through this type of launch?  Asking as our current launch is passing these ID’s as variables to the API in the call so they can return it, as I will be using these to conform a SQL statement to post the obs ID’s back to the active document from the launch.
Would be good to get a better understanding of this process and what is passed as a possible future iteration.   I just know we are currently on a tight schedule to get this rolled out so I don’t want to hold that up if we can get the account authentication to work properly.

Thanks,
Jeremy Carr

CELL 773.580.0099
***@***.******@***.***>

**Comment by AOCjcarr** [comment]
@Torin-Shepard-athena 
Torin-- Thanks again for all of the guidance.  This afternoon @dwwinters  and I worked through some adjustments based on the guidance from #177  and we are successfully connecting now.
The launch from the button in the clinical content is able to launch their app, which in turn is making several calls to aP utilizing he saved AAD credentials and authenticating properly without the prompt for the user input!
Jeremy
