### ISSUE TITLE
Create Appointment Call Syntax

### ISSUE THREAD

**Issue by SRJBritt** [athenahealth/apiserver-athenaFlex#209]
I am trying to send a create appointment API call but it returns with the following exception that I can't for the life of me find documentation for what to include in the system and display variables:
```
{
	"resourceType": "OperationOutcome",
	"text": {
		"status": "generated",
		"div": " Outcome null#SeverityTypeDetail1ERRORBUSINESSRULEAppointment type coding.system is missing.2ERRORBUSINESSRULEAppointment type coding.display is missing. "
	},
	"issue": [
		{
			"severity": "error",
			"code": "business-rule",
			"diagnostics": "Appointment type coding.system is missing."
		},
		{
			"severity": "error",
			"code": "business-rule",
			"diagnostics": "Appointment type coding.display is missing."
		}
	]
}
```
For reference this is the body I am sending to the API, and this is for a Centricity database using AthenaFlow:
```
<Appointment>
    <status value="proposed"/>
    <start value="2021-10-25T08:30:00.000Z"/>
    <end value="2021-10-25T08:45:00.000Z"/>
    <minutesDuration value="15"/>
    <participant>
        <actor>
            <reference value="Patient/112723"/>
        </actor>
    </participant>
    <participant>
        <type>
            <coding>
                <code value="73"/>
            </coding>
        </type>
        <actor>
            <reference value="Practitioner/84"/>
        </actor>
    </participant>
    <participant>
        <actor>
            <reference value="Location/FAC-24"/>
        </actor>
    </participant>
</Appointment>
```
And I was thinking that the changes needed to be made would be:
```
        <type>
            <coding>
                <code value="73"/>
                <system value="http://hl7.org/fhir/ValueSet/c80-practice-codes"/>
                <display value="Well 15"/>
            </coding>
        </type>
```

**Comment by Torin-Shepard-athena** [comment]
@SRJBritt
Please use ability to read Appointment resources to discover/learn values expected for different elements.

Example:  Appointment?patient=1239620410000620 should return the appointments for test patient Walter Caldell in an athenaFlow tutorial database.

Although Appointment.type is considered optional in FHIR specification, it is mandatory in athenaFlow to specify the type of appointment being booked.  There are other mandatory elements needed to create appointments through FHIR API.

Some of the id values you have will work for athenaPractice but will not work for athenaFlow which in uses 16-digit numbers for Patient, Practitioner, Location.  We realize this may not be obvious since we currently provide API sandboxes for athenaPractice.  With our V22 release, we plan to have API sandboxes for both athenaFlow and athenaPractice.

Here is an example Appointment resource that can be used to book an appointment for a future date.

```xml
<Appointment>
	<extension url="http://hl7.org/fhir/StructureDefinition/ge-appointment-booklist">
		<valueString value=":1226313962051060.000000:"/>
	</extension>
	<status value="booked"/>
	<start value="2021-10-25T08:30:00.000Z"/>
	<end value="2021-10-25T08:45:00.000Z"/>
	<minutesDuration value="15"/>
	<type>
		<coding>
			<system value="http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF"/>
			<code value="1226328755001060"/>
			<display value="Est Office 15 min"/>
		</coding>
		<text value="Est Office 15 min"/>
	</type>
	<participant>
		<actor>
			<reference value="Patient/1239620410000620"/>
		</actor>
		<status value="tentative"/>
	</participant>
	<participant>
		<type>
			<coding>
				<system value="http://hl7.org/fhir/v3/ParticipationType"/>
				<code value="PPRF"/>
				<display value="primary performer"/>
			</coding>
			<text value="primary performer"/>
		</type>
		<actor>
			<reference value="Practitioner/1225652472001060"/>
		</actor>
		<status value="tentative"/>
	</participant>
	<participant>
		<actor>
			<reference value="Location/1225648184001060"/>
		</actor>
		<status value="tentative"/>
	</participant>
</Appointment>
```

FYI: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks explains how triple back-quotes can be used to indicate format of code blocks posted in GitHub issues.

**Comment by SRJBritt** [comment]
Thanks for all the information and the example you provided!
