### ISSUE TITLE
date-fromnow parameter for Observation

### ISSUE THREAD

**Issue by tthai4** [athenahealth/apiserver-athenaFlex#220]
@Torin-Shepard-athena,
I am trying to understand the usage of the date-fromnow parameter in the Observation request.  Lets say, a patient has 2 sets of Observation which documented on 2021-11-03 and 2021-10-02.  If I do not use the date-fromnow parameter in the request, the response does contain 2 sets of Observation as expected.  (see request URL below)

https://apiuf.emrconnect.org:9443/ufAPIServer/fhir/Observation?_count=30000&_include=Observation%3Aperformer&_tag%3Anot=FiledInError&code%3Ain=ValueSet%3Fname%3DFlowsheet+zz_Alliance_Aspire&date-fromnow=le-7%7C%7Cd&status%3Anot=entered-in-error&subject=1597794857700560

Now, lets say I am only interested in the most recent set (2021-11-03) and so I am adding the date-fromnow=le-7%7C%7Cd parameter to the  original request (see request URL  below). 

https://apiuf.emrconnect.org:9443/ufAPIServer/fhir/Observation?_count=30000&_include=Observation%3Aperformer&_tag%3Anot=FiledInError&code%3Ain=ValueSet%3Fname%3DFlowsheet+zz_Alliance_Aspire&date-fromnow=le-7%7C%7Cd&status%3Anot=entered-in-error&subject=1597794857700560

I would expect the response to contain the set of Observation with effective date = 2021-11-03 but what I received is the other set which has effective date = 2021-10-02.

If I am interested in all Observation set that were documented within the past 12 months, I would use date-fromnow=le-12%7C%7Cmo in the request.  For this request, I am getting nothing back.  

Is date-fromnow=le-XX||date-unit parameter is the right one to use if you are interested in those Observations that were documented in the past XX days or months?  

Thank you very much for your help.

TT

**Comment by Torin-Shepard-athena** [comment]
@tthai4 
The modifier translates to a comparison using the value specified in the date-fromnow search parameter.

Observations whose effectiveTime is within the last 12 months.
date-fromnow=**ge**-XX||mo means any time on or after (greater than or equal to) XX months before today

Observations whose effectiveTime is more than 12 months before today.
date-fromnow=**lt**-XX|mo means any time before (less than) XX months before today.

fromnow date parameters are specified as =[prefix]value||unit where:
value is a signed integer and unit specifies the precision of the range adjustment.

The date is adjusted up or down by value units
Units are UCUM unit values: s Seconds min Minutes h Hours d Days mo Months a Years

NOTE: Weeks are not supported because they do not fit evenly into other units. A week can span two different years.

If now is: 2017-07-20T05:01:39 the following parameters will be:

| search value | interpretation |
| ------------ | -------------- |
| date-fromnow=-1\|\|a | 2016 |
| date-fromnow=-12\|\|mo | date is in the month of 2016-07 (e.g. between 2016-07-01 and 2016-07-31) |
| date-fromnow=-365\|\|d | 2017-07-20 (but only because this is not a leap year!) |
| date-fromnow=1\|\|a | 2018 |
| date-fromnow=-1\|\|m | 2017-06 |
| date-fromnow=-30\|\|d | 2017-06-20 (but only because June has 30 days!) |
| date-fromnow=1\|\|d | 2017-07-21 |
| date-fromnow=24\|\|h | 2017-07-21:05 |
| date-fromnow=0\|\|d | 2017-07-20 |
| date-fromnow=-1\|\|h | 2017-07-21T04 |
| date-fromnow=-1\|\|m | 2017-07-21T05:00 |

Et cetera

date-fromnow=0||UNIT means any time in "this UNIT"
date-fromnow=-1||UNIT means any time in the previous UNIT.
date-fromnow=lt-1||UNIT means any time before the previous UNIT
date-fromnow=gt1||unit means any time after the next UNIT

**Comment by AjeetYadav07** [comment]
This issue has been responded and no further communication received from customer end,  We are closing this issue.
