### ISSUE TITLE
Receiving updates for any change in the resources (Appointment, Slot, Patient, Schedule, Coverage, Location and Practitioner).

### ISSUE THREAD

**Issue by mumtaz-t9** [athenahealth/apiserver-athenaFlex#240]
How do I receive updates for a change in any of the resources listed below? 

- Appointment
- Slot
- Schedule
- Patient 
- Practitioner
- Coverage
- Location

Does AthenaPractice supports subscription resource as per FHIR standards: https://hl7.org/fhir/subscription.html ?  or do they have an alternative mechanism of pushing updates to the external system?

We are developing a system that will cache the above listed resources and would keep them in sync with the source-resources at the Athena FHIR server. We would like to know how does AthenaPractice sends updates to the external systems for the changes to any of the above listed resources?

**Comment by AjeetYadav07** [comment]
Does AthenaPractice supports subscription resource as per FHIR standards: https://hl7.org/fhir/subscription.html ?
Yes, we are supporting subscription resource as per FHIR standard. We used to send updated status with the URL of particular resource(API) that meet the criteria in the resource cause a notification. Please read the developer portal documentation https://mydata.athenahealth.com/fhirapidoc/r4.
(https://docs.mydata.athenahealth.com/fhir-r4/artifacts.html)Profile - Athena Subscription

**Comment by mumtaz-t9** [comment]
Hi Ajeet, 
Thank you for the detailed information, I have tried to subscribe a rest-hook but am getting an error: _"Subscription end point check failed with error message as: Unable to contact the endpoint mentioned in the request"_

I have used the following sandbox URL and resource structure:

URL: https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Subscription

Subscription Resource Structure: 
`{
    "resourceType" : "Subscription",
    "status" : "requested",
    "reason" : "T9 test subscription", 
    "criteria" : "Patient?name=T9",
    "channel" : { 
      "type" : "rest-hook", 
      "endpoint" : "https://f451guc44b.execute-api.us-east-1.amazonaws.com/dev/subscription",
      "header": "Bearer 123456789"
    }
  }`

When I send a POST subscription request to the FHIR REST server I get the following error: 

`"issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Subscription end point check failed with error message as : Unable to contact the endpoint mentioned in the request"
        }`

I have tested the channel endpoint that I've given in the structure using postman and it works fine. 
Please let me know if I am missing something? Thanks!

**Comment by AjeetYadav07** [comment]
Hi @mumtaz-t9,

The endpoint where the channel points should be http supported call not https. For your reference will be providing payload and subscription endpoint through which you can post Subscriptions. 
[Subscription_post_payload.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/9099689/Subscription_post_payload.txt)

**Comment by mumtaz-t9** [comment]
Hi @AjeetYadav07
I tried with an HTTP endpoint but now getting a different error given below: 
`"issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Subscription end point is not accessiable. It returned response code as : 470."
        }
    ]`

Further, The .txt file you have posted looks like a reference to how we can obtain tokens and not the subscription payload. can you please double check and give a sample body/payload for the subscription post request. Thanks

**Comment by AjeetYadav07** [comment]
Hi @mumtaz-t9,
 
Uploaded a wrong file. Here is the correct payload for subscription.
[subscription_payload.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/9108691/subscription_payload.txt)

**Comment by mumtaz-t9** [comment]
Hi @AjeetYadav07 ,
Thanks for sharing the payload sample - however I am still getting the same **error** given below:

**Error Message:** 
`Subscription end point is not accessiable. It returned response code as : 470.`

I am attaching the payload and server response/error when I try to post a subscription resource as per the attached payload to the URL: `https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Subscription`

[subscription_payload_used.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/9112872/subscription_payload_used.txt)
[error_message_470.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/9112875/error_message_470.txt)

Looking forward to a solution - Thanks

**Comment by AjeetYadav07** [comment]
Hi Mumtaz, As per our Implementation we support only the below endpoint
        <endpoint value="http://localhost:8181/api/test/post/subscription"/>
ie athenaflex FHIR server supports only the above endpoint for subscription to work. The endpoint you have provided is different and hence you are getting this error. Please change the endpoint to above mentioned endpoint for Subscription payload to work. Hope this clarifies.

**Comment by mumtaz-t9** [comment]
Hi Ajeet,
It looks like you might have left out pasting the endpoint, but we tried adding a subscription with an endpoint at http://localhost:8181/ which was accepted, but that doesn't help us much because we can't actually put up an endpoint at the address localhost that the FHIR service can connect to.  Part of what we're trying to test in the sandbox is receiving actual update notifications in our system for development, so we would like to subscribe with a URL we can actually receive events at.  We can't receive events at localhost, so being able to subscribe with localhost urls doesn't really help our testing and development.  Is it just not possible to register outside event handlers with subscription creation?

**Comment by stonstad** [comment]
I am also interested in the answer to @mumtaz-t9 's question.

**Comment by Torin-Shepard-athena** [comment]
@mumtaz-t9 @stonstad @AjeetYadav07 

Making a successful connection to the Subscription notification endpoint is one of the validation rules performed when attempting to create a Subscription.  The networks must be configured so the FHIR Server is allowed to make outbound requests to the subscription endpoint.  This may require configuration for both the network where the FHIR Server resides and the network where the Subscription client resides.

For my testing of athenaPractice FHIR Subscription notification, I have used a free POST test server available at http://ptsv2.com.  This server works for both http and https.

http://ptsv2.com/s/whatisthis.html explains this is a service that you can receive your POSTS and GETS and dump them so you know what is being transmitted.

Although the FHIR Server accepts http and https in Subscription.criteria URLs, it appears athena network policy may allow only outbound https but not http.  ptsv2 is not accessible from ap22sandbox with only http.  ap22sandbox machine attempts to send http requests to ptsv2 get denied due to athenahealth deny outbound firewall policy rules.

More research is needed to determine if external Subscription client endpoints are accessible from ap22sandbox with https.

At this time, ap22sandbox sees "unexpectedly closed the connection" error response from https request attempts to both amazonws and ptsv2.

There could be multiple, different notification endpoints for various 3rd party Subscription client apps. This creates challenges in determining how to configure the network for our API Sandbox machines.

There does not seem to be an easy answer or simple solution for testing FHIR Subscriptions with our API Sandbox machines.  Since we cannot predict what Subscription client endpoints will be for various 3rd party applications, it seems problematic to maintain a list of allowed endpoints without involvement from both athena and 3rd party Cloud Ops teams.

It may be easier and/or more practical to find and work with an athenaPractice or athenaFlow customer that can make the required configurations to enable their FHIR Server to post notifications your Subscription client endpoint(s).

**Comment by stonstad** [comment]
Thank you for the detailed and very helpful response. This helps us plan and it gives us an idea of how to proceed with development.  Thank you!

**Comment by mumtaz-t9** [comment]
Thank you @Torin-Shepard-athena!
