### ISSUE TITLE
Clinical Outbound using CCDA.

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#257]
As mentioned in the documentation AllergyIntolerance, FamilyMemberHistory and Procedure supports only Read. So is there any alternate way to post these data to Athena ?

I also see that CCDA 2.1 is supported, can we use this to post the data ?

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/metadata and the API documentation pages for the CapabilityStatement show create is supported for DocumentReference.

In athenaPractice and athenaFlow, DocumentReference POST can be used to create Chart documents that contain RTF or XML content.

NOTE: When you use FHIR API or athenaPractice/athenaFlow client applications to import CCDAs, the CCDA is created as a document a patient chart,  The structured entries are not automatically incorporated into the clinical lists in the chart.  This happens only when a practitioner chooses to perform optional clinical reconciliation.

Chart documents created from DocumentReference resources will be routed to the Practitioner reference in the authenticator element.  This Practitioner must have permissions to sign the Chart doc type specified in the type element.

DocRef create API supports CCDA XML as the body of the document by using content.attachment.data with Base64 encoded XML. With this workflow, the XML content must be a CCDA document because the athenaPractice/athenaFlow client applications do not support any other kind of XML content for Chart documents.

DocRef.content for RTF or XML document body
``` xml
   <description value="Chart document summary"/>
    <content>
        <attachment>
            <contentType value="text/xml" /> <!-- or value="text/rtf" -->
            <data value="Base64-encoded-document-content-matching-content-type"/>
        </attachment>
    </content>
```

The following postings have more information about using POST DocumentReference to create documents and then access them after they are created.
#28
#62
#88

In athenaPractice, DocumentReference POST can also be used to create Ppatient profile attachments and patient visit attachments.  This is not supported in athenaFlow which does not have these practice management features.  We can give you more information about this if needed.

DocumentReference PUT is supported for patient profile attachments and patient visit attachments in athenaPractice. It is not supported for updating chart documents in either athenaPractice or athenaFlow.
