### ISSUE TITLE
Insurance Relationship and Insurance Packages

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#263]
According to Coverage API’s documentation, coverage.relationship should be part of the response. 
When I tried with couple of test patients even by adding relationship as part of coverage, I did not get this data as part of the response.   

One other question is about Insurance Package – do we have an API to get the list of Health Insurance Plan/Packages supported?  
This list is required for coverage update/create.

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
relationship element is not supported because [R4 Coverage Resource](http://hl7.org/fhir/R4/coverage.html) defines relationship as optional element with cardinality 0..1 and because athenaPractice/athenaFlow may not have appropriate mappings to SubscriberPolicyholder Relationship Codes value set.

The policyHolder, subscriber, subscriberId, beneficiary elements are output when they have been captured, entered by the office staff using athenaPractice/athenaFlow applications.
